version: '3.3'
services:
  postgresql:
    image: postgres:10
    container_name: cash_flow_ex-postgres
    environment:
      - POSTGRES_DB=cash_flow_ex_dev
      - POSTGRES_PASSWORD=development
    ports:
      - 5433:5432
    volumes:
      - cash_flow_ex_psql:/var/lib/postgresql/data
volumes:
  cash_flow_ex_psql:
